name: Build Container Image
on: push
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        id: branch
        run: echo "::set-output name=name::$(BRANCH_NAME=${GITHUB_REF##*/}; echo ${BRANCH_NAME/release_/})"
      - run: docker build . -t almahmoud/biocondcutor_docker:${{ steps.branch.outputs.name }}
      - name: Login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: actions-hub/docker@master
        with:
          args: push almahmoud/bioconductor_docker:${{ steps.branch.outputs.name }}
